export const FLEX_ATTRIBUTE_PROPS = [
  'background',
  'height',
  'width',
  'minHeight',
  'minWidth',
  'padding',
  'margin',
  'zIndex',
  'transition',
  'borderRadius',
  'borderColor',
  'borderStyle',
  'borderWidth',
  'border',
  'borderTop',
  'borderRight',
  'borderBottom',
  'borderLeft',
  'boxShadow',
] as const
